### ISSUE TITLE
ugh

### ISSUE THREAD

**Issue by fayercx2931** [HeyItsMeNobody/Kyuko#1]
ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh ugh

**Comment by fayercx2931** [comment]
wait how do i add profile pic

**Comment by HeyItsMeNobody** [comment]
No spam :sob:
